
[package]
edition = "2024"
name = "xosms"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi-derive = "3.0.0"
tokio = { version = "1.53.1", features = ["sync", "time"] }

[dependencies.napi]
version = "3.0.0"
features = ["napi4", "async"]

[target.'cfg(target_os = "linux")'.dependencies]
zbus = { version = "5.19.0", features = ["tokio"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows-core = "0.100"
windows-time = "0.100"
windows-strings = "0.100"
windows-future = "0.100"
windows-collections = "0.100"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6"
objc2-foundation = "0.3"
objc2-core-foundation = "0.3"
objc2-app-kit = "0.3"
objc2-media-player = "0.3"
block2 = "0.6"
libuv-sys2 = "1.52"

[build-dependencies]
napi-build = "2"
windows-bindgen = "0.100"

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"
