/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A MediaPlayer instance that provides independent information and controls */
export declare class MediaPlayer {
  /**
   * Creates a MediaPlayer instance
   *
   * @param serviceName - A unique id for the MediaPlayer which cannot be re-used while active
   * @param identity - A display name for the MediaPlayer
   */
  constructor(serviceName: string, identity: string)
  /**
   * Activates this MediaPlayer by starting the platform backend
   *
   * @remarks Behavior differs when {@link platformSharesMediaPlayers} is true
   */
  activate(): Promise<void>
  /**
   * Deactivates this MediaPlayer by stopping the platform backend
   *
   * @remarks Behavior differs when {@link platformSharesMediaPlayers} is true
   */
  deactivate(): Promise<void>
  /**
   * Updates the platform backend with the latest state
   *
   * @remarks Behavior differs when {@link platformSharesMediaPlayers} is true
   */
  update(): Promise<void>
  /**
   * Sets the timeline data
   *
   * This function does not require {@link MediaPlayer.update} to be called and immediately sends changes to the platform backend
   */
  setTimeline(duration: number, position: number): Promise<void>
  /**
   * Sets the callback when the media service sends a button press
   *
   * If this callback is a {@link Promise} xosms will wait for it to resolve
   * @remarks {@link Promise} based callbacks will have errors silently discarded
   */
  setButtonPressedCallback(callback: (button: ButtonPressedType) => Promise<void> | void): void
  /**
   * Sets the callback when the media service sends a position change
   *
   * If this callback is a {@link Promise} xosms will wait for it to resolve
   * @remarks {@link Promise} based callbacks will have errors silently discarded
   */
  setPositionChangedCallback(callback: (position: number) => Promise<void> | void): void
  /**
   * Sets the callback when the media service sends a position seek
   *
   * If this callback is a {@link Promise} xosms will wait for it to resolve
   * @remarks {@link Promise} based callbacks will have errors silently discarded
   */
  setPositionSeekedCallback(callback: (offset: number) => Promise<void> | void): void
  /**
   * Sets the callback when the media service sends a loop change
   *
   * If this callback is a {@link Promise} xosms will wait for it to resolve
   * @remarks {@link Promise} based callbacks will have errors silently discarded
   */
  setLoopChangedCallback(callback: (loop: LoopType) => Promise<void> | void): void
  /**
   * Sets the callback when the media service sends a playback rate change
   *
   * If this callback is a {@link Promise} xosms will wait for it to resolve
   * @remarks {@link Promise} based callbacks will have errors silently discarded
   */
  setRateChangedCallback(callback: (rate: number) => Promise<void> | void): void
  /**
   * Sets the callback when the media service sends a shuffle change
   *
   * If this callback is a {@link Promise} xosms will wait for it to resolve
   * @remarks {@link Promise} based callbacks will have errors silently discarded
   */
  setShuffleChangedCallback(callback: (shuffle: boolean) => Promise<void> | void): void
  /**
   * Sets the callback when the media service sends a volume change
   *
   * If this callback is a {@link Promise} xosms will wait for it to resolve
   * @remarks {@link Promise} based callbacks will have errors silently discarded
   */
  setVolumeChangedCallback(callback: (volume: number) => Promise<void> | void): void
  get playButtonEnabled(): boolean
  set playButtonEnabled(enabled: boolean)
  get pauseButtonEnabled(): boolean
  set pauseButtonEnabled(enabled: boolean)
  get stopButtonEnabled(): boolean
  set stopButtonEnabled(enabled: boolean)
  get previousButtonEnabled(): boolean
  set previousButtonEnabled(enabled: boolean)
  get nextButtonEnabled(): boolean
  set nextButtonEnabled(enabled: boolean)
  get seekEnabled(): boolean
  set seekEnabled(enabled: boolean)
  get fullscreen(): boolean
  set fullscreen(enabled: boolean)
  get playbackRate(): number
  set playbackRate(rate: number)
  get minimumPlaybackRate(): number
  set minimumPlaybackRate(rate: number)
  get maximumPlaybackRate(): number
  set maximumPlaybackRate(rate: number)
  get shuffle(): boolean
  set shuffle(enabled: boolean)
  get loop(): LoopType
  set loop(loop: LoopType)
  get volume(): number
  set volume(value: number)
  get playbackStatus(): PlaybackStatus
  set playbackStatus(status: PlaybackStatus)
  get title(): string
  set title(value: string)
  get artist(): Array<string>
  set artist(value: Array<string>)
  get albumTitle(): string
  set albumTitle(value: string)
  get trackId(): string
  set trackId(value: string)
  get thumbnail(): MediaPlayerThumbnail | null
  set thumbnail(value: MediaPlayerThumbnail | undefined | null)
  /** Disposes this MediaPlayer releasing all native resources */
  dispose(): void
}

/** A MediaPlayerThumbnail instance which may hold native resources for the platform to use on a MediaPlayer */
export declare class MediaPlayerThumbnail {
  /**
   * Creates a MediaPlayerThumbnail instance
   *
   * @param thumbnailType - The type of thumbnail being created
   * @param thumbnail - A uri or file path pointing to the thumbnail
   */
  static create(thumbnailType: MediaPlayerThumbnailType, thumbnail: string): Promise<MediaPlayerThumbnail>
  get thumbnailType(): MediaPlayerThumbnailType
}

export type ButtonPressedType =  'play'|
'pause'|
'playpause'|
'stop'|
'next'|
'previous';

export type LoopType =  'none'|
'track'|
'playlist';

export type MediaPlayerThumbnailType =  'file'|
'uri';

/** Indicates whether this platform shares all instances of MediaPlayer */
export declare function platformSharesMediaPlayers(): boolean

export type PlaybackStatus =  'playing'|
'paused'|
'stopped';
