name: Build & Test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install libdbus
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt-get install libdbus-1-dev pkg-config -y 
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn build:lib
    - name: Library Test
      if: ${{ matrix.ois != 'ubuntu-latest' }} # DBus doesn't exist in CI and this test will always fail
      run: yarn test
    - name: Native Test
      run: yarn cargo:test
